name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'notes-app-backend/**'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ReviseX
            
            # Ensure sparse checkout is still set (safe to run every time)
            git sparse-checkout init --cone
            git sparse-checkout set notes-app-backend

            # Pull only backend changes
            git pull origin main

            # Go into backend
            cd notes-app-backend

            # Install dependencies safely
            npm ci

            # Restart only backend process (CHANGE NAME)
            pm2 restart all
